### ISSUE TITLE
Backlog: Add Kindara API integration

### ISSUE THREAD

**Issue by machikoyasuda** [SaraChicaD/flo#1]
As a [Kindara](http://kindara.com) user, I would like to be able to:
1. Export my current Kindara data as CSV
2. Import my current Kindara data CSV into Flo

I built a Ruby wrapper for the backend to fetch data: https://github.com/machikoyasuda/kindara-client-gem

**Comment by SaraChicaD** [comment]
don't know what Kindara is, but we need to get to the point where we can create a Flo calendar to add events to before we can import/export :P I'll keep you in the loop.

**Comment by machikoyasuda** [comment]
Definitely :)
