### ISSUE TITLE
Error at Google Authorization

### ISSUE THREAD

**Issue by machikoyasuda** [SaraChicaD/flo#10]
How do I get a proper Google Client ID?
1. I logged into https://console.developers.google.com/apis/library
   ![screen shot 2016-10-01 at 12 27 34 pm](https://cloud.githubusercontent.com/assets/3673236/19016637/417935e8-87d5-11e6-8d77-ab6e90748e59.png)
2. Clicked `Credentials`
   ![screen shot 2016-10-01 at 12 46 46 pm](https://cloud.githubusercontent.com/assets/3673236/19016638/4736cb80-87d5-11e6-9b2a-887e7ea28f64.png)
3. Clicked `Create Credentials` and then `OAuth client ID`
   ![screen shot 2016-10-01 at 12 46 56 pm](https://cloud.githubusercontent.com/assets/3673236/19016639/4a9d297c-87d5-11e6-8663-57e3a9cd579c.png)
4. Chose `Web Application` and clicked `Create`
   ![screen shot 2016-10-01 at 12 49 43 pm](https://cloud.githubusercontent.com/assets/3673236/19016647/929bcb48-87d5-11e6-82c7-8511142e79d2.png)
5. Got a window showing a unique client ID and client secret, copied the client ID.

I copied the client ID, which ends in `apps.googleusercontent.com` into line 2 of the `config.json` file. Then I ran `gulp config` and then `npm start`. I am able to get into `http://localhost:8000` but after I click `Authorize`, I get this error:

![screen shot 2016-10-01 at 12 52 13 pm](https://cloud.githubusercontent.com/assets/3673236/19016656/f6c24840-87d5-11e6-9ee7-97d5749d64af.png)

What am I doing wrong? I would love to help out by adding documentation, README.md to make it easier for other people to use this app! <3 Thanks for making this open source.

**Comment by machikoyasuda** [comment]
I figured it out!!!!! Thank you @SaraChicaD for the tip.

The error I made was that I did not add `localhost:8000` to the authorized JavaScript origins.

Instructions:
https://developers.google.com/identity/sign-in/web/devconsole-project

Part II: Make sure you authorize Google Calendar API specifically - or else you'll get an error message like this:

```
"Access Not Configured. Calendar API has not been used in project ####### before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/calendar/overview?project=###### then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
```

**Comment by SaraChicaD** [comment]
thanks @machikoyasuda i hope i was helpful, glad it worked out :)

**Comment by arsalan** [comment]
Great work Sara! 

```
On Monday, October 3, 2016 1:43 PM, Sara Inés Calderón <notifications@github.com> wrote:
```

 thanks @machikoyasuda i hope i was helpful, glad it worked out :) —
